USE hospital;
SELECT *
FROM `sales dataset`;

ALTER TABLE `sales dataset`
RENAME sales_dataset;

ALTER TABLE sales_dataset
CHANGE COLUMN `Order ID`  Order_Id VARCHAR(50);

ALTER TABLE sales_dataset
CHANGE COLUMN `Order Date`  Order_Date DATE;

ALTER TABLE sales_dataset
RENAME COLUMN `Year-Month` TO  Period;

ALTER TABLE sales_dataset
CHANGE COLUMN `Sub-Category` Sub_category VARCHAR(50);

-- TOTAL CUSTOMERS
SELECT COUNT(DISTINCT customername) customer_population
FROM sales_dataset; -- 802

-- TOTAL PROFIT EARNED
SELECT sum(profit) total_profit
FROM sales_dataset; -- 1610697

-- Yearly Sales growth
SELECT
	((SUM(year_25_profit)-SUM(year_24_profit))/SUM(year_24_profit) )*100 AS YoY_sales_25_24,
	((SUM(year_24_profit)-SUM(year_23_profit))/SUM(year_23_profit) )*100 AS YoY_sales_24_23,
	((SUM(year_23_profit)-SUM(year_22_profit))/SUM(year_22_profit) )*100 AS YoY_sales_23_22,
	((SUM(year_22_profit)-SUM(year_21_profit))/SUM(year_21_profit) )*100 AS YoY_sales_22_21,
	((SUM(year_21_profit)-SUM(year_20_profit))/SUM(year_20_profit) )*100 AS YoY_sales_21_20
FROM(
SELECT Order_Date,
(CASE WHEN year(Order_Date)=2025 THEN SUM(profit) END) year_25_profit,
 (CASE WHEN year(Order_Date)=2024 THEN SUM(profit) END) year_24_profit,
 (CASE WHEN year(Order_Date)=2023 THEN SUM(profit) END) year_23_profit,
 (CASE WHEN year(Order_Date)=2022 THEN SUM(profit) END) year_22_profit,
 (CASE WHEN year(Order_Date)=2021 THEN SUM(profit) END) year_21_profit,
 (CASE WHEN year(Order_Date)=2020 THEN SUM(profit) END) year_20_profit
FROM sales_dataset
GROUP BY Order_Date)TT;

-- YEARLY CUSTOMERS ACQUISITION
SELECT 
((sum(year_25_customer)-sum(year_24_customer))/sum(year_24_customer)) *100 CAR_25,
((sum(year_24_customer)-sum(year_23_customer))/sum(year_23_customer)) *100 CAR_24,
((sum(year_23_customer)-sum(year_22_customer))/sum(year_22_customer)) *100 CAR_23,
((sum(year_22_customer)-sum(year_21_customer))/sum(year_21_customer)) *100 CAR_22,
((sum(year_21_customer)-sum(year_20_customer))/sum(year_20_customer)) *100 CAR_21
FROM (
SELECT Order_Date,
(CASE WHEN year(Order_Date)=2025 THEN count(CustomerName) END) year_25_customer,
 (CASE WHEN year(Order_Date)=2024 THEN count(CustomerName) END) year_24_customer,
 (CASE WHEN year(Order_Date)=2023 THEN count(CustomerName) END) year_23_customer,
 (CASE WHEN year(Order_Date)=2022 THEN count(CustomerName) END) year_22_customer,
 (CASE WHEN year(Order_Date)=2021 THEN count(CustomerName) END) year_21_customer,
 (CASE WHEN year(Order_Date)=2020 THEN count(CustomerName) END) year_20_customer
 FROM sales_dataset
 GROUP BY Order_Date)tt;

-- TOTAL QUANTITY SOLD
SELECT sum(quantity) total_quantity_sold
FROM sales_dataset; -- 12745

-- PROFIT GENERATED BY CATEGORY
SELECT Category, sum(Profit) profit_generated
FROM sales_dataset
GROUP BY Category
ORDER BY sum(Profit) DESC;

-- PROFIT GENERATED BY Sub_category
SELECT Sub_category, sum(Profit) profit_generated
FROM sales_dataset
GROUP BY Sub_category
ORDER BY sum(Profit) DESC;

-- QUANTITY SOLD BY CATEGORY
SELECT Category, sum(quantity) quantity_sold
FROM sales_dataset
GROUP BY Category
ORDER BY sum(quantity) DESC;

-- QUANTITY SOLD BY SUB_CATEGORY
SELECT Sub_category, sum(quantity) quantity_sold
FROM sales_dataset
GROUP BY Sub_category
ORDER BY sum(quantity) DESC;

-- CUSTOMERS PAYMENT MODE PREFERENCE
SELECT PaymentMode, COUNT(PaymentMode)
FROM sales_dataset
GROUP BY PaymentMode
ORDER BY COUNT(PaymentMode) DESC;

-- WHO ARE OUR TOP CUSOMERS BY PROFIT AND QUANTITY BOUGHT
SELECT CustomerName, State, Sub_category, profit_generated, SUM(quantity) quantity_bought
FROM(
SELECT CustomerName, State, Sub_category, sum(profit) profit_generated, quantity
FROM sales_dataset
GROUP BY CustomerName, State, Sub_category, quantity
ORDER BY sum(profit) DESC)TT
GROUP BY CustomerName, State, Sub_category, profit_generated
ORDER BY  SUM(quantity) DESC; -- profit_generated DESC;

-- CUSTOMERS POPULATION ACROSS CITY, QUANTITY ORDERED AND PROFIT GENERATED
SELECT state, count(customername) customer_population, SUM(quantity) quantity_total, sum(profit) profit_generated
FROM sales_dataset
GROUP BY state
ORDER BY  count(customername) DESC;